# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Configure
      run: mkdir build && cd build && cmake G Xcode ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest
    - name: package
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_SHA: ${{ github.sha }}
      run: bash script/package.sh
    - name: upload
      uses: shallwefootball/s3-upload-action@v1.0.1
      with:
        aws_key_id: ${{ secrets.S3_ID }}
        aws_secret_access_key: ${{ secrets.S3_KEY }}
        aws_bucket: cycling74-ci-public
        source_dir: 'dist'
  
